const baseColors=[
  ['Pink','#ffa4bd'],['Blue','#729edf'],['Lime','#bfd449'],['Green','#3f894e'],['Yellow','#ffe284'],['Purple','#9f5a9d'],['Dark Pink','#cd3a6e'],['Cyan','#5ee1d3'],['Orange','#ffb166'],['Dark Blue','#5871d6'],['Coral','#ef8a70'],['Teal','#55b8a9'],['Violet','#8f79c9'],['Gold','#d7aa42'],['Sky','#6bb8e8']
];
const example=[[0,0,0,1,1,1,0,0,0,0],[2,2,0,3,3,1,1,0,6,6],[2,2,0,3,4,4,5,0,0,6],[2,2,0,3,4,4,5,5,0,6],[2,2,0,7,4,5,5,5,0,6],[2,2,0,7,7,7,8,8,0,6],[2,2,0,7,7,8,8,8,0,0],[9,2,0,0,0,0,8,8,8,0],[9,9,9,9,9,0,8,8,8,0],[9,9,0,0,0,0,0,0,0,0]];
let size=10,board=example.map(r=>r.slice()),selected=0,scanImage=null;
const $=id=>document.getElementById(id);
function paletteFor(n){const p=baseColors.slice(0,n);while(p.length<n){const i=p.length,h=Math.round((i*137.508)%360);p.push([`Color ${i+1}`,`hsl(${h} 65% 70%)`])}return p}
function colors(){return paletteFor(size)}
function blankBoard(n){return Array.from({length:n},()=>Array(n).fill(null))}
function setSize(n,loadBlank=true){size=n;$('size').value=String(n);selected=Math.min(selected,n-1);board=loadBlank?blankBoard(n):example.map(r=>r.slice());dogs=Array(n).fill(-1);$('solution').style.display='none';$('status').textContent=loadBlank?`${n}×${n} board created. Paint the colors, then press Solve.`:'10×10 example loaded. Press Solve.';legend();render()}
let dogs=Array(size).fill(-1);
function legend(){const cs=colors();$('legend').innerHTML=cs.map((x,i)=>`<button class="swatch ${i===selected?'selected':''}" data-i="${i}"><span class="dot" style="background:${x[1]}"></span>${i+1}: ${x[0]}</button>`).join('');document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{selected=+b.dataset.i;legend()})}
function render(){const cs=colors(),g=$('grid');g.style.gridTemplateColumns=`repeat(${size},1fr)`;g.innerHTML='';for(let r=0;r<size;r++)for(let c=0;c<size;c++){const b=document.createElement('button'),colorIndex=board[r][c];b.className='cell'+(colorIndex===null?' empty':'')+(dogs[r]===c?' fox solution':'');b.style.setProperty('--cell-color',colorIndex===null?'#fff':cs[colorIndex][1]);b.title=colorIndex===null?`R${r+1} C${c+1}: Empty`:`R${r+1} C${c+1}: ${cs[colorIndex][0]}`;b.onclick=()=>{board[r][c]=selected;dogs.fill(-1);$('solution').style.display='none';$('status').textContent='Board changed. Press Solve.';render()};g.appendChild(b)}}
function solve(){dogs.fill(-1);const cs=colors();let nodes=0;if(board.some(row=>row.some(cell=>cell===null))){$('status').textContent='⚠️ Please paint every cell before solving.';$('solution').style.display='none';render();return}const cols=new Set(),usedColors=new Set();function legal(r,c){if(cols.has(c)||usedColors.has(board[r][c]))return false;for(let rr=0;rr<size;rr++)if(dogs[rr]>=0&&Math.abs(rr-r)<=1&&Math.abs(dogs[rr]-c)<=1)return false;return true}function dfs(n){nodes++;if(n===size)return true;let br=-1,bc=[];for(let r=0;r<size;r++){if(dogs[r]>=0)continue;const a=[];for(let c=0;c<size;c++)if(legal(r,c))a.push(c);if(!a.length)return false;if(br<0||a.length<bc.length){br=r;bc=a}}for(const c of bc){dogs[br]=c;cols.add(c);usedColors.add(board[br][c]);if(dfs(n+1))return true;cols.delete(c);usedColors.delete(board[br][c]);dogs[br]=-1}return false}if(dfs(0)){$('status').textContent=`✅ Solution found for ${size}×${size} (${nodes.toLocaleString()} search nodes)`;$('solution').textContent=dogs.map((c,r)=>`Row ${r+1} → Column ${c+1} → ${cs[board[r][c]][0]}`).join('\n');$('solution').style.display='block';render()}else{$('status').textContent=`❌ No solution found for ${size}×${size}`;render()}}
function rgbToHsv(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;return[d/(mx||1),mx]}
function patchStats(data,w,h,cx,cy,rad){const vals=[];const x0=Math.max(0,Math.round(cx-rad)),x1=Math.min(w-1,Math.round(cx+rad)),y0=Math.max(0,Math.round(cy-rad)),y1=Math.min(h-1,Math.round(cy+rad));for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const i=(y*w+x)*4;vals.push([data[i],data[i+1],data[i+2]])}const mean=[0,1,2].map(k=>vals.reduce((s,v)=>s+v[k],0)/vals.length);const variance=vals.reduce((s,v)=>s+(v[0]-mean[0])**2+(v[1]-mean[1])**2+(v[2]-mean[2])**2,0)/vals.length;const med=[0,1,2].map(k=>{const a=vals.map(v=>v[k]).sort((a,b)=>a-b);return a[Math.floor(a.length/2)]});return {color:med,variance}}
function dist(a,b){return Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2])}
function kmeans(samples,k){let centers=[];for(let i=0;i<k;i++)centers.push(samples[Math.floor(i*samples.length/k)].slice());for(let pass=0;pass<12;pass++){const groups=Array.from({length:k},()=>[]);for(const s of samples){let bi=0,bd=Infinity;for(let j=0;j<k;j++){const d=dist(s,centers[j]);if(d<bd){bd=d;bi=j}}groups[bi].push(s)}for(let j=0;j<k;j++)if(groups[j].length)centers[j]=[0,1,2].map(q=>Math.round(groups[j].reduce((sum,s)=>sum+s[q],0)/groups[j].length))}let sse=0;for(const s of samples){let bd=Infinity;for(const c of centers)bd=Math.min(bd,dist(s,c));sse+=bd*bd}return {centers,sse}}
function detectBoard(){if(!scanImage)return;const c=$('previewCanvas'),ctx=c.getContext('2d',{willReadFrequently:true}),w=c.width,h=c.height,d=ctx.getImageData(0,0,w,h).data,step=Math.max(1,Math.floor(Math.min(w,h)/240)),W=Math.ceil(w/step),H=Math.ceil(h/step),mask=new Uint8Array(W*H);for(let y=0;y<H;y++)for(let x=0;x<W;x++){const i=(Math.min(h-1,y*step)*w+Math.min(w-1,x*step))*4,[s,v]=rgbToHsv(d[i],d[i+1],d[i+2]);mask[y*W+x]=(s>.10&&v>.20)?1:0}
  let best=null;
  for(let s=Math.floor(Math.min(W,H)*.20);s<=Math.floor(Math.min(W,H)*.95);s+=2){for(let y=0;y+s<=H;y+=2){for(let x=0;x+s<=W;x+=2){let hit=0,total=0;for(let yy=y;yy<y+s;yy+=3)for(let xx=x;xx<x+s;xx+=3){hit+=mask[yy*W+xx];total++}const density=hit/total;const borderPenalty=(mask[y*W+x]+mask[Math.max(y+s-1,y)*W+Math.max(x+s-1,x)]);const score=density*s*s;if(!best||score>best.score)best={x,y,s,score,density,borderPenalty}}}}
  if(!best||best.density<.08){$('status').textContent='⚠️ Grid not detected. Try a screenshot containing the full puzzle board.';return}
  const bx=best.x*step,by=best.y*step,bw=best.s*step;
  let bestN=10,bestScore=Infinity,bestBoard=null;
  for(let n=4;n<=15;n++){
    const samples=[],variances=[];const rad=Math.max(1,bw/n*.10);
    for(let r=0;r<n;r++)for(let col=0;col<n;col++){const p=patchStats(d,w,h,bx+(col+.5)*bw/n,by+(r+.5)*bw/n,rad);samples.push(p.color);variances.push(p.variance)}
    const km=kmeans(samples,n);const avgVar=variances.reduce((a,b)=>a+b,0)/variances.length;const avgSse=km.sse/samples.length;
    const minSep=(()=>{let m=Infinity;for(let i=0;i<km.centers.length;i++)for(let j=i+1;j<km.centers.length;j++)m=Math.min(m,dist(km.centers[i],km.centers[j]));return m})()||0;
    const score=avgVar*0.65+avgSse*1.2-Math.min(minSep,120)*0.35;
    if(score<bestScore){bestScore=score;bestN=n;bestBoard=samples}}
  size=bestN;$('size').value=String(size);board=Array.from({length:size},(_,r)=>bestBoard.slice(r*size,(r+1)*size).map(rgb=>{let best=0,bd=Infinity;const cs=colors();cs.forEach((c,i)=>{const hex=c[1].replace('#','');const target=[parseInt(hex.slice(0,2),16),parseInt(hex.slice(2,4),16),parseInt(hex.slice(4,6),16)];const dd=dist(rgb,target);if(dd<bd){bd=dd;best=i}});return best}));dogs=Array(size).fill(-1);selected=0;$('scanPreview').hidden=true;$('status').textContent=`📷 Screenshot scanned. Detected ${size}×${size}. Check the colors, then press Solve.`;legend();render()}
$('scanButton').onclick=()=>$('imageInput').click();$('imageInput').onchange=e=>{const file=e.target.files?.[0];if(!file)return;$('scanName').textContent=file.name;const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{scanImage=img;const c=$('previewCanvas'),scale=Math.min(1,1400/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);$('scanPreview').hidden=false;$('status').textContent='Screenshot loaded. Tap Auto Detect Board.'};img.src=reader.result};reader.readAsDataURL(file)};$('detectButton').onclick=detectBoard;$('closePreview').onclick=()=>{$('scanPreview').hidden=true};
$('size').onchange=()=>setSize(+$('size').value,true);$('newBoard').onclick=()=>setSize(+$('size').value,true);$('solve').onclick=solve;$('clearDogs').onclick=()=>{dogs.fill(-1);$('solution').style.display='none';$('status').textContent='Foxes cleared.';render()};$('example').onclick=()=>{if(size!==10){$('size').value='10';size=10}board=example.map(r=>r.slice());dogs=Array(10).fill(-1);selected=0;$('solution').style.display='none';$('status').textContent='10×10 example loaded. Press Solve.';legend();render()};$('clearBoard').onclick=()=>{board=blankBoard(size);dogs.fill(-1);$('solution').style.display='none';$('status').textContent=`${size}×${size} board cleared.`;render()};$('size').value='10';legend();render();